name       : yices2          # name of the package
version    : 2.4.1-1       # version of the package
kind       : tool                     # one of tool or spec(s)
description: Yices 2 is an SMT solver that decides the satisfiability of formulas containing uninterpreted function symbols with equality, linear real and integer arithmetic, bitvectors, scalar types, and tuples.

author:
  - name: John L. Singleton
    email: jsinglet@gmail.com


assets:
    - asset   : MAIN
      name    : Yices2 Distribution for Windows 
      url     : "http://yices.csl.sri.com/cgi-bin/yices2-newnewdownload.cgi?file=yices-2.4.1-x86_64-pc-mingw32-static-gmp.zip&accept=I+Agree"
      platform: windows
    - asset   : MAIN
      name    : Yices2 Distribution for OSX
      url     : "http://yices.csl.sri.com/cgi-bin/yices2-newnewdownload.cgi?file=yices-2.4.1-x86_64-apple-darwin14.4.0-static-gmp.tar.gz&accept=I+Agree"
      platform: osx
    - asset   : MAIN
      name    : Yices2 Distribution for Linux
      url     : "http://yices.csl.sri.com/cgi-bin/yices2-newnewdownload.cgi?file=yices-2.4.1-x86_64-unknown-linux-gnu-static-gmp.tar.gz&accept=I+Agree"
      platform: linux
        

install:
  - cmd: unzip MAIN
    description: Unpacking Windows Distribution
    platform: windows
  - cmd: tar -zxvf  MAIN
    description: Unpacking OSX Distribution
    platform: osx
  - cmd: tar -zxvf MAIN
    description: Unpacking Linux Distribution
    platform: linux
  - cmd: cp yices-2.4.1/bin/yices.exe yices.exe
    description: Restructuring...
    platform: windows
  - cmd: ln -s yices-2.4.1/bin/yices yices
    description: Restructuring...
    platform: linux
  - cmd: ln -s yices-2.4.1/bin/yices yices.bin
    description: Linking binary...
    platform: osx
  - cmd: mv yices.osx.sh yices
    description: Adding OSX Shims...
    platform: osx
  - cmd: chmod +x yices
    description: Setting Shim Executable...
    platform: osx
